-- Custom interaction modes must be registered before the doors using them spawn.
Package.Require("CustomModes.lua")

-- Import the MapDoors.lua file generated by the export_doors.py script
Package.Require("MapDoors.lua")
