-- Generated by nanos-door/Content/Python/export_doors.py from level 'BlankMap' on 2026-09-24 17:46.
-- Do not edit by hand: move the BP_DoorMarker actors in Unreal and re-export.
-- Requires the `door` package (list it in packages_requirements).
return BaseDoor.SpawnFromList({
    { type = "Hinge", location = Vector(-300, 800, 100), rotation = Rotator(0, 0, 90), mode = "trigger", asset = "nanos-world::SM_Plane", slide_offset = Vector(0, 100, 0) }, -- BP_DoorMarker
    { type = "Sliding", location = Vector(600, 500, 100), rotation = Rotator(0, 0, 90), mode = "timed", asset = "nanos-world::SM_Plane", slide_offset = Vector(0, 100, 0) }, -- BP_DoorMarker2
})
